### ISSUE TITLE
Reached max retry

### ISSUE THREAD

**Issue by iCeManxTT** [derekhe/msfs2020-map-enhancement#517]
Error

Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:

Run in administrator mode
Close any software that occupies 443 or 42098 port
Add this software into antivirus whitelist
Completely reinstall this software
Visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) and [Issue page](https://github.com/derekhe/msfs2020-map-enhancement/issues)
Detail: Error: Reached max retry

**Comment by ilyabumblebee** [comment]
Try running backend manually (core.exe in releases folder), wait until it loads up, and then run frontend.

**Comment by derekhe** [comment]
This problem should be solved. Please check.

**Comment by gobbone** [comment]
which servers?

**Comment by dermatti2** [comment]
@derekhe, unfortunately the issue is still happening on my machine, Win 11, MapEnhancement 7.5.3. It does not occur after a fresh installation. 

Here is how to reproduce: 
* Fresh install
* Play game
* End game 
* Reboot machine
* Try to start again

It seems that something does not shutdown properly after playing the game. Because MSFS wants to start in safe-mode after the reboot too. How should i close MapEnchancement properly to avoid this?

**Comment by derekhe** [comment]
Please try close the mod or click "stop" after you End game. 
Reboot machine may kill the mod instantly and the mod don't have a chance to restore the hosts file which may cause some issues.

**Comment by dermatti2** [comment]
> Please try close the mod or click "stop" after you End game. Reboot machine may kill the mod instantly and the mod don't have a chance to restore the hosts file which may cause some issues.

Yes, thanks. This seemed to be indeed the cause of my problems. 
An idea for an improvement:
a) Show a warning message right at the start of the program or even better
b) listen for shutdown events to cleanly shutdown directly.

Thanks anyway,
your add-on is great!!!
