### ISSUE TITLE
Problem displaying ArcGIS in immediate vicinity of user aircraft since v4

### ISSUE THREAD

**Issue by robmw1** [derekhe/msfs2020-map-enhancement#75]
**Describe the bug**
Since versions after 4.0 there seems to be a problem with ArcGIS tiles immediately surrounding the aircraft at high LOD levels. These are appearing as blank tiles with 'Data not yet available' watermarked on them. This problem is also visible in the flight selection map so can be easily tested without loading a full flight. It seems that all the other map servers are ok. I also tried the new high LOD feature with ArcGIS but it did not help.

The last version I have tried where this problem does not occur is 3.2.4.

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: steam
 - MSFS2020 Version 1.23.12 (SU8)

**Log** 
Please provide the logs:
Will provide if needed

**Additional context**

**Comment by derekhe** [comment]
Can you check if it is fixed in latest version?

**Comment by robmw1** [comment]
Hi,
I don't see any version later than 4.2.1 so I assume you've made some changes in the back-end?
Anyway, just checked again with 4.2.1 and the same problem is still there. To be clear, it only occurs at the very highest level of zoom in the flight selection map. One zoom level back and the tiles are ok. Unfortunately the highest level of zoom is what is visible from the aircraft during 'low and slow' flying. The other map servers show lower resolution tiles which is fine (note also that the high-def enhancement does not make any difference with this problem with ArcGIS tiles).
With v3.2.4 lower res tiles were visible at the highest zoom level but sometimes higher res tiles would appear, I guess if these were available from the server.
I've attached logs this time as requested in your message at flightsim.to. Hopefully the zip won't be blocked for you.
Thanks
(BTW - Just wanted to let you know I'm a donor - I'll keep using this mod until something happens with the map providers or MS to limit it's usefulness, hopefully not for a while yet if ever or until MS sort out their imagery)
    On Wednesday, 16 March 2022, 11:23:50 GMT, hesicong ***@***.***> wrote:  
 
 


Can you check if it is fixed in latest version?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by derekhe** [comment]
@robmw1 I tested ArcGIS yesterday and didn't see the problem. Could you verify this problem again? Please also attach the screenshots and location you find the problem.

**Comment by a543150176** [comment]
I also have this problem, which also exists in version 4.2.1.

**Comment by robmw1** [comment]
Hi,
Yes, it is fixed now. Saw the new version yesterday and gave it a go.
Many thanks for the support. 
    On Monday, 4 April 2022, 03:48:30 BST, a543150176 ***@***.***> wrote:  
 
 


I also have this problem, which also exists in version 4.2.1.

**Comment by Bjorn7711** [comment]
I still have this problem with version 4.2.2. Attached is a screenshot where you can see the white tiles creeping up under the plane, more and more  as it approaches the ground landing at ENDU. Logs422 is from this, and logs324 is from a similar landing running version 3.2.4. where this problem does not happen. 
Sometimes you have to wait a bit, pause the sim when you fly low, look down, wait maybe 10-20 secs, and the white tiles start to appear.
 
![LandingENDU](https://user-images.githubusercontent.com/101942794/162576023-0bdab9c9-e3e4-4de3-bd6e-28ac73cc16f6.jpg)
[logs422.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8457007/logs422.zip)
[logs324.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8457008/logs324.zip)

**Comment by derekhe** [comment]
Fix in this version: https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v4.2.3
